# Generated by Django 3.2 on 2023-12-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Best_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default=None, max_length=12)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default=None, max_length=12)),
                ('name', models.CharField(default=None, max_length=1000)),
                ('price', models.CharField(default=None, max_length=10)),
                ('ISBN', models.CharField(default=None, max_length=15)),
                ('author', models.CharField(default=None, max_length=1000)),
                ('publisher', models.CharField(default=None, max_length=50)),
                ('img', models.ImageField(default=None, upload_to='')),
                ('website', models.CharField(default=None, max_length=120)),
                ('sales', models.IntegerField(default=0, max_length=10)),
                ('comment1', models.CharField(max_length=512)),
                ('comment2', models.CharField(max_length=512)),
                ('comment3', models.CharField(max_length=512)),
                ('comment4', models.CharField(max_length=512)),
                ('comment5', models.CharField(max_length=512)),
                ('comment6', models.CharField(max_length=512)),
                ('comment7', models.CharField(max_length=512)),
                ('comment8', models.CharField(max_length=512)),
                ('comment9', models.CharField(max_length=512)),
                ('comment10', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='hot_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('num', models.CharField(default=None, max_length=12)),
                ('name', models.CharField(default=None, max_length=1000)),
                ('score', models.IntegerField(default=1)),
                ('price', models.CharField(default=None, max_length=10)),
                ('ISBN', models.CharField(default=None, max_length=15)),
                ('author', models.CharField(default=None, max_length=1000)),
                ('publisher', models.CharField(default=None, max_length=50)),
                ('img', models.ImageField(default=None, upload_to='')),
                ('website', models.CharField(default=None, max_length=120)),
                ('sales', models.IntegerField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
